In [13]:
import numpy as np
arr=np.array([2,4,6,8])
print(arr.shape)
print(arr.dtype)
print(arr.ndim)
print(np.mean(arr))
print(np.max(arr))
print(np.min(arr))


(4,)
int32
1
5.0
8
2


In [5]:
matrix=np.array([[1,2,3],[5,6,7]])
print(matrix[0,1])
print(matrix[:,1])

2
[2 6]


In [9]:
a=np.array([[1,2],[3,4]])
a_reshaped=a.reshape(4,)

In [11]:
a=np.array([1,2,3])
b=np.array([4,4,6])
print(a+b)
print(a-b)
print(a*2)
print(a*b)

[5 6 9]
[-3 -2 -3]
[2 4 6]
[ 4  8 18]
